### ISSUE TITLE
[PE-D] Sort Command Error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#260]
![image.png](https://raw.githubusercontent.com/rohit0718/ped/main/files/4b56de44-f7ef-430d-8382-b54225f2b92e.png)

Doing a `sort x/time o/asc` moved a task with date `0001-01-01` to past `9999-12-01`, which is desc.

Same goes for desc command:

![image.png](https://raw.githubusercontent.com/rohit0718/ped/main/files/477b6082-7b0d-4a55-b424-d985d41aabe1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: rohit0718/ped#13

**Comment by naranghardik16** [comment]
I think the functionality of the sort command was not clear in the UG. 
The sort command only sorts the tasks based on time (not date) and priority. The reason behind sorting tasks only based time is soleIy to sort the tasks on the same day and get a better view in the weekly calendar. 
I will update that in the UG so that users don't get confused while using the sort command. 
Thanks for pointing this out.
