### ISSUE TITLE
[PE-D] Sort command doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#272]
I added two tasks into the app and wanted to sort them by time, so I typed in "sort x/time o/desc", but the sort command didn't work.

Before:
![9.1.png](https://raw.githubusercontent.com/HongshuW/ped/main/files/4f8740f4-db14-429e-9ec8-7aafff60ee53.png)
After:
![9.2.png](https://raw.githubusercontent.com/HongshuW/ped/main/files/30829ba7-5798-4cae-8b21-48eebfcdf7ba.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: HongshuW/ped#9

**Comment by naranghardik16** [comment]
The sort command does not sort the task list instead it sorts the tasks by time and priority in the weekly view. This is the reason why the sort command is not working in this case. 

So the sort commands use is only to sort the tasks of a particular day with respect to time and priority. 

I will update this thing in the UG since I think it was not that clear before. I will always try to make the sort command sort the task list so that it makes much more sense. 

Thanks for pointing this out.
